name: build jupyterhub image
on:
  push:
    paths:
      - .github/workflows/repo2docker.yaml
      - environment.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout files in repo
        uses: actions/checkout@v4
      - name: move repo2docker files
        run: |
          mv environment.yml .
      - name: build with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          LATEST_TAG_OFF: false
          REPO_DIR: /srv
          FORCE_REPO2DOCKER_VERSION: "git+https://github.com/jupyterhub/repo2docker@5d3a946b24608f1856218eb89861d552e9b826af"
